apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: code-server
  name: code-server-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: manual

