version: "3.8"

services:
  mydb:
    image: stackupiss/northwind-db:v1
    container_name: mydb
    networks:
      - mynet
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: changeit

  myapp:
    image: stackupiss/northwind-app:v1
    container_name: myapp
    networks:
      - mynet
    ports:
      - "8080:3000"
    environment:
      DB_HOST: mydb
      DB_USER: root
      DB_PASSWORD: changeit

networks:
  mynet:

volumes:
  db-data:

