apiVersion: apps/v1
kind: Deployment
metadata:
  name: bggdb-deploy
  namespace: bggns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bggdb
  template:
    metadata:
      labels:
        app: bggdb
    spec:
      containers:
        - name: bggdb
          image: stackupiss/bgg-database:v1
          ports:
            - containerPort: 3306
---
apiVersion: v1
kind: Service
metadata:
  name: bggdb-svc
  namespace: bggns
spec:
  selector:
    app: bggdb
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  clusterIP: None